baseURL = 'http://zoomacode.net/'
languageCode = 'en-us'
title = 'Chaotic thoughts'
theme = "ananke"
copyright = "Anton Golubtsov"
description = "A collection of random thoughts on random topics"
googleAnalytics = "G-57DD980L5H"
disqusShortname = 'ChaoticThoughts'

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/zoomacode"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/zoomacode"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/zoomacode/"

[[params.ananke_socials]]
name = "keybase"
url = "https://keybase.io/zoomacode"