baseURL: 'https://chaotic.land/'
languageCode: en-us
defaultContentLanguage: en
title: Chaotic Thoughts
theme: PaperMod
copyright: Anton Golubtsov
description: A collection of random thoughts on random topics from software engineering to mushrooms
googleAnalytics: G-96GHV7J9Q8
favicon: favicon.png
enableEmoji: true

taxonomies:
  tag: tags

languages:
  en:
    disabled: false
    weight: 1
    languageCode: en-us
    languageName: En
  ru:
    disabled: false
    weight: 2
    languageCode: ru
    languageName: Ru

menu:
  main:
    - identifier: about
      name: About
      pageRef: /about/
      weight: -100
    - identifier: posts
      name: Posts
      pageRef: /posts/
      weight: -130
    - identifier: book-review
      name: Book reviews
      pageRef: /book-reviews/
      weight: -120
    - identifier: Jobs To Be Done 47
      name: JTBD
      pageRef: /jobs-to-be-done-47/
      weight: -110
    - identifier: RSS
      name: RSS
      url: /feed.xml
      weight: -90

    - identifier: newsletter
      name: Newsletter
      url: https://buttondown.com/zoomacode
      weight: -85

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowShareButtons: true
  ShowToc: true
  TocOpen: false
  disableSpecial1stPost: true
  homeInfoParams:
    Content: A collection of random thoughts on random topics from software engineering to mushrooms.
  mainSections:
    - posts
    - book-reviews
  socialIcons:
    - name: x
      url: 'https://twitter.com/zoomacode'
    - name: github
      url: 'https://github.com/zoomacode'
    - name: linkedin
      url: 'https://www.linkedin.com/in/zoomacode/'
    - name: keybase
      url: 'https://keybase.io/zoomacode'
    - name: mastodon
      url: 'https://mastodon.social/@zoomacode'
  newsletter:
    url: https://buttondown.com/zoomacode
    form_action: https://buttondown.com/api/emails/embed-subscribe/zoomacode
  author:
    name: Anton Golubtsov
    email: logrusadm@gmail.com
    url: https://chaotic.land/

outputFormats:
  rss:
    mediatype: application/rss+xml
    baseName: feed      # Rename RSS feed URL from rss.xml to feed.xml
